(()=>{
'use strict';
// Кабинет репетитора: ученики, расписание, домашние задания (ссылки-варианты + журнал), оплата.
// Данные: localStorage + синхронизация по коду кабинета в KV (/cabinet/<код>). Подключается после trainer-upgrade-v4.js.
if(!window.v4)return;
const V4=window.v4,d=document;
const KEY='oge-ege-2027-cabinet',KEY_CODE='oge-ege-2027-cabinet-code',KEY_TOK='oge-ege-2027-cabinet-token',KEY_MAIL='oge-ege-2027-cabinet-email';
const AUTH=null;
const API=V4.JOURNAL_API.replace(/journal\/$/,'cabinet/');const AUTH_API=V4.JOURNAL_API.replace(/journal\/$/,'auth/');
const ls={get:k=>{try{return localStorage.getItem(k)||''}catch{return''}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}},del:k=>{try{localStorage.removeItem(k)}catch{}}};
const token=()=>ls.get(KEY_TOK),email=()=>ls.get(KEY_MAIL);
async function authFetch(path,body){const h={'Content-Type':'application/json'};if(token())h.Authorization='Bearer '+token();const r=await fetch(AUTH_API+path,{method:body?'POST':'GET',headers:h,body:body?JSON.stringify(body):undefined});let j={};try{j=await r.json()}catch{}return{status:r.status,...j}}
// восстановить кабинет по токену сессии (вход по почте)
async function restoreSession(){if(!token())return false;const r=await authFetch('me');if(r.ok&&r.cabinet){ls.set(KEY_CODE,r.cabinet);ls.set(KEY_MAIL,r.email);return true}if(r.status===401){ls.del(KEY_TOK);ls.del(KEY_MAIL)}return false}
const uid=()=>Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-3);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmtD=iso=>{const [y,m,dd]=iso.split('-');return `${dd}.${m}.${y}`};
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n))+' ₽';
const DOW=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const toISO=t=>`${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-${String(t.getDate()).padStart(2,'0')}`;
const todayISO=()=>toISO(new Date());
const addDays=(iso,n)=>{const t=new Date(iso+'T00:00:00');t.setDate(t.getDate()+n);return toISO(t)};
const mondayOf=iso=>{const t=new Date(iso+'T00:00:00');const k=(t.getDay()+6)%7;return addDays(iso,-k)};

// ---------- данные ----------
let DB=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.students))return x}catch{}return{students:[],lessons:[],homework:[],payments:[],updatedAt:0}}
let syncTimer=0;
function save(){DB.updatedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify(DB))}catch{}clearTimeout(syncTimer);syncTimer=setTimeout(pushRemote,800)}
function code(){try{return localStorage.getItem(KEY_CODE)||''}catch{return''}}
function newCode(){const a='abcdefghijklmnopqrstuvwxyz0123456789';const r=crypto.getRandomValues(new Uint8Array(16));let s='';for(const b of r)s+=a[b%a.length];return s}
async function pushRemote(){const c=code();if(!c)return;try{const r=await fetch(API+c,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(DB)});if(r.status===409){const j=await r.json();if(j.server){DB=j.server;try{localStorage.setItem(KEY,JSON.stringify(DB))}catch{}render()}}setSync(r.ok?'ok':'err')}catch{setSync('err')}}
async function pullRemote(c){try{const r=await fetch(API+c);if(!r.ok)return false;const j=await r.json();if(j&&Array.isArray(j.students)){if(Number(j.updatedAt)>=Number(DB.updatedAt)){DB=j;try{localStorage.setItem(KEY,JSON.stringify(DB))}catch{}}else pushRemote()}setSync('ok');return true}catch{setSync('err');return false}}
function setSync(st){const el=d.querySelector('#cabSync');if(!el)return;el.textContent=st==='ok'?'синхронизировано':st==='err'?'нет связи, данные сохранены локально':'';el.className='cab-sync '+st}
// журналы из движка (ссылки-варианты) + связь с учеником
function journals(){return V4.loadJ()}
window.onVariantLinkCreated=entry=>{const sid=window.cabinetStudentId;if(!sid)return;DB.homework.push({id:uid(),studentId:sid,journalId:entry.id,sub:entry.sub,label:entry.label,link:entry.link,created:Date.now()});save()};

// ---------- расчёты ----------
const student=id=>DB.students.find(s=>s.id===id);
const lessonsOf=id=>DB.lessons.filter(l=>l.studentId===id).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
const paymentsOf=id=>DB.payments.filter(p=>p.studentId===id).sort((a,b)=>b.date.localeCompare(a.date));
function balance(id){const done=lessonsOf(id).filter(l=>l.status==='done').length;const paidLessons=paymentsOf(id).reduce((a,p)=>a+(Number(p.lessons)||0),0);const paidMoney=paymentsOf(id).reduce((a,p)=>a+(Number(p.amount)||0),0);return{done,paidLessons,paidMoney,left:paidLessons-done}}
function nextLesson(id){const t=todayISO();return lessonsOf(id).find(l=>l.status==='planned'&&l.date>=t)}
function lastDone(id){return lessonsOf(id).filter(l=>l.status==='done').slice(-1)[0]}

// ---------- UI ----------
const css=d.createElement('style');css.textContent=`
#cabinet{width:min(1040px,calc(100% - 20px));max-height:calc(100dvh - 20px);border:0;border-radius:22px;padding:0;background:#fffdf8;color:#17231d;box-shadow:0 24px 80px #071b1280}
#cabinet::backdrop{background:#10271db8;backdrop-filter:blur(5px)}
#cabinet *{box-sizing:border-box}.cab-wrap{padding:22px 24px;max-height:calc(100dvh - 20px);overflow:auto}
.cab-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}.cab-head h2{margin:2px 0 4px;font-size:26px}.cab-kicker{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:#187653;font-weight:800}
.cab-close{border:0;background:#edf0eb;width:40px;height:40px;border-radius:50%;font-size:22px;cursor:pointer}
.cab-tabs{display:flex;gap:8px;margin:14px 0;flex-wrap:wrap}.cab-tab{border:1px solid #d8dfd9;background:#fff;border-radius:999px;padding:8px 14px;font-weight:800;cursor:pointer;font-size:13px}.cab-tab.on{background:#187653;color:#fff;border-color:#187653}
.cab-btn{border:0;border-radius:12px;padding:10px 14px;background:#187653;color:#fff;font-weight:800;cursor:pointer;font-size:13px}.cab-btn.sec{background:#e8eee9;color:#183d2c}.cab-btn.danger{background:#fae9e7;color:#8b2821}.cab-btn.sm{padding:6px 10px;font-size:12px}
.cab-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:10px 0}
.cab-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:10px}
.cab-card{border:1px solid #d8dfd9;border-radius:14px;padding:12px 14px;background:#fff;cursor:pointer;text-align:left}.cab-card:hover{border-color:#187653}.cab-card b{display:block;font-size:16px}.cab-card small{color:#667269;display:block;margin-top:3px}
.cab-pill{display:inline-block;border-radius:999px;padding:2px 9px;font-size:11.5px;font-weight:800;background:#e8f6ef;color:#12603f}.cab-pill.warn{background:#fff4d7;color:#72520b}.cab-pill.bad{background:#fae9e7;color:#8b2821}
.cab-week{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.cab-day{border:1px solid #d8dfd9;border-radius:12px;padding:8px;min-height:120px;background:#fff}.cab-day.today{border-color:#187653;box-shadow:inset 0 0 0 1px #187653}.cab-day h4{margin:0 0 6px;font-size:12px;color:#667269}.cab-day h4 b{color:#17231d;font-size:14px}
.cab-ls{display:block;width:100%;text-align:left;border:0;border-radius:8px;padding:6px 8px;margin:4px 0;background:#e8f6ef;font-size:12px;cursor:pointer;line-height:1.3}.cab-ls.done{background:#eef2ee;opacity:.75}.cab-ls.cancelled{background:#fae9e7;text-decoration:line-through}
.cab-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px;border:1px solid #d8dfd9;border-radius:14px;padding:12px;background:#fafbf8;margin:10px 0}.cab-form label{font-size:12px;color:#667269;display:block}.cab-form input,.cab-form select,.cab-form textarea{width:100%;border:1px solid #ccd6cf;border-radius:10px;padding:9px;font-size:16px;font:inherit;font-size:15px}.cab-form .full{grid-column:1/-1}
.cab-sec{border:1px solid #d8dfd9;border-radius:14px;padding:14px;margin:12px 0;background:#fff}.cab-sec h3{margin:0 0 8px;font-size:16px}
table.cab-t{border-collapse:collapse;width:100%;font-size:13px}.cab-t th,.cab-t td{border-bottom:1px solid #e7ece8;padding:7px 8px;text-align:left;vertical-align:top}.cab-t th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#667269}
.cab-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px}.cab-stat{border-radius:12px;background:#f4f8f5;padding:10px 12px}.cab-stat b{display:block;font-size:22px}.cab-stat span{font-size:11px;color:#667269;text-transform:uppercase;letter-spacing:.06em}
.cab-sync{font-size:12px;color:#667269}.cab-sync.err{color:#8b2821}.cab-muted{color:#667269;font-size:13px}
.cab-btn-top{border:0;border-radius:999px;padding:10px 16px;background:#e8f6ef;color:#12603f;font-weight:800;cursor:pointer;margin-right:8px}
@media(max-width:780px){.cab-week{grid-template-columns:1fr}.cab-day{min-height:auto}.cab-wrap{padding:16px}.cab-head h2{font-size:20px}}
.cab-sec{overflow-x:auto}.cab-sec .cab-t{min-width:420px}
@media(max-width:560px){.cab-btn-top{padding:8px 10px;font-size:12px;margin-right:4px}.top .topright{flex-wrap:wrap;justify-content:flex-end;row-gap:4px}.top .guide-btn,.top .room-btn{padding:8px 10px;font-size:12px}}
`;d.head.append(css);

const dlg=d.createElement('dialog');dlg.id='cabinet';dlg.innerHTML='<div class="cab-wrap"></div>';d.body.append(dlg);
dlg.onclick=e=>{if(e.target===dlg)dlg.close()};
const wrap=dlg.querySelector('.cab-wrap');
let view={tab:'schedule',week:mondayOf(todayISO()),student:null,form:null};

// Ждём закрытия чужого диалога (событие close в некоторых webview не приходит — следим за атрибутом open)
function whenClosed(el,cb){let done=false;const fin=()=>{if(done)return;done=true;mo.disconnect();el.removeEventListener('close',fin);cb()};const mo=new MutationObserver(()=>{if(!el.open)fin()});mo.observe(el,{attributes:true,attributeFilter:['open']});el.addEventListener('close',fin)}
function open(){render();if(!dlg.open)dlg.showModal();const c=code();if(c)pullRemote(c).then(()=>render());else if(token())restoreSession().then(ok=>{if(ok)pullRemote(code()).then(()=>render())})}
function render(){
 const c=code();
 wrap.innerHTML=`<div class="cab-head"><div><div class="cab-kicker">Кабинет репетитора</div><h2>${view.student?esc(student(view.student)?.name||'Ученик'):'Ученики, расписание, оплата'}</h2><div id="cabSync" class="cab-sync"></div></div><div><button class="cab-btn sec sm" id="cabCode">${email()?esc(email()):c?'Код кабинета':'Войти'}</button> <button class="cab-close" id="cabClose">×</button></div></div>
 <div class="cab-tabs">${[['schedule','Расписание'],['students','Ученики'],['pay','Оплата'],['code',email()?'Аккаунт':'Вход']].map(([k,t])=>`<button class="cab-tab ${view.tab===k&&!view.student?'on':''}" data-tab="${k}">${t}</button>`).join('')}${view.student?`<button class="cab-tab on">Карточка ученика</button>`:''}</div>
 <div id="cabBody"></div>`;
 wrap.querySelector('#cabClose').onclick=()=>dlg.close();
 wrap.querySelector('#cabCode').onclick=()=>{view.student=null;view.tab='code';render()};
 wrap.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{view.student=null;view.tab=b.dataset.tab;view.form=null;render()});
 const body=wrap.querySelector('#cabBody');
 if(view.student)renderStudent(body);else if(view.tab==='schedule')renderSchedule(body);else if(view.tab==='students')renderStudents(body);else if(view.tab==='pay')renderPay(body);else renderCode(body);
 setSync(c?(navigator.onLine?'ok':'err'):'');
}
function lessonLabel(l){const s=student(l.studentId);return `${l.time||''} ${esc(s?.name||'—')}${l.topic?' · '+esc(l.topic):''}`}
function renderSchedule(body){
 const days=[...Array(7)].map((_,i)=>addDays(view.week,i));const t=todayISO();
 body.innerHTML=`<div class="cab-row"><button class="cab-btn sec sm" id="wPrev">← неделя</button><b>${fmtD(days[0])} — ${fmtD(days[6])}</b><button class="cab-btn sec sm" id="wNext">неделя →</button><button class="cab-btn sec sm" id="wToday">Сегодня</button><span style="flex:1"></span><button class="cab-btn" id="lAdd">+ Урок</button></div>
 ${view.form==='lesson'?lessonForm():''}
 <div class="cab-week">${days.map((iso,i)=>{const ls=DB.lessons.filter(l=>l.date===iso).sort((a,b)=>(a.time||'').localeCompare(b.time||''));return `<div class="cab-day ${iso===t?'today':''}"><h4>${DOW[i]} <b>${iso.slice(8)}</b></h4>${ls.map(l=>`<button class="cab-ls ${l.status}" data-l="${l.id}">${lessonLabel(l)}</button>`).join('')||'<div class="cab-muted">—</div>'}</div>`}).join('')}</div>
 <div class="cab-sec"><h3>Ближайшие уроки</h3>${upcomingTable()}</div>`;
 body.querySelector('#wPrev').onclick=()=>{view.week=addDays(view.week,-7);render()};body.querySelector('#wNext').onclick=()=>{view.week=addDays(view.week,7);render()};body.querySelector('#wToday').onclick=()=>{view.week=mondayOf(todayISO());render()};
 body.querySelector('#lAdd').onclick=()=>{view.form=view.form==='lesson'?null:'lesson';render()};
 bindLessonForm(body);body.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>lessonMenu(b.dataset.l));
}
function upcomingTable(){const t=todayISO();const ls=DB.lessons.filter(l=>l.status==='planned'&&l.date>=t).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,8);if(!ls.length)return'<div class="cab-muted">Запланированных уроков нет. Нажмите «+ Урок».</div>';return `<table class="cab-t"><tr><th>Дата</th><th>Время</th><th>Ученик</th><th>Тема</th><th></th></tr>${ls.map(l=>`<tr><td>${fmtD(l.date)}</td><td>${esc(l.time)}</td><td><a href="#" data-st="${l.studentId}">${esc(student(l.studentId)?.name||'—')}</a></td><td>${esc(l.topic||'')}</td><td><button class="cab-btn sm" data-done="${l.id}">Проведён</button></td></tr>`).join('')}</table>`}
function lessonForm(sid){const sts=DB.students;const l=view.editLesson||{};return `<form class="cab-form" id="lForm"><input type="hidden" name="id" value="${l.id||''}"><div><label>Ученик</label><select name="studentId" required>${sts.map(s=>`<option value="${s.id}" ${(sid||l.studentId)===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div><label>Дата</label><input type="date" name="date" value="${l.date||todayISO()}" required></div><div><label>Время</label><input type="time" name="time" value="${l.time||'16:00'}" required></div><div><label>Длительность, мин</label><input type="number" name="duration" value="${l.duration||60}" min="15" step="15"></div><div class="full"><label>Тема урока</label><input name="topic" value="${esc(l.topic||'')}" placeholder="Например: №15–17 геометрия"></div><div><label>Повторять еженедельно, недель</label><input type="number" name="repeat" value="1" min="1" max="20"></div><div class="full cab-row"><button class="cab-btn" type="submit">${l.id?'Сохранить':'Добавить в расписание'}</button><button class="cab-btn sec" type="button" id="lCancel">Отмена</button>${sts.length?'':'<span class="cab-muted">Сначала добавьте ученика во вкладке «Ученики».</span>'}</div></form>`}
function bindLessonForm(body){const f=body.querySelector('#lForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);const id=fd.get('id');const rep=id?1:Math.max(1,Number(fd.get('repeat'))||1);for(let i=0;i<rep;i++){const rec={id:id||uid(),studentId:fd.get('studentId'),date:addDays(fd.get('date'),7*i),time:fd.get('time'),duration:Number(fd.get('duration'))||60,topic:String(fd.get('topic')||'').trim(),status:'planned',note:''};if(id){const ix=DB.lessons.findIndex(x=>x.id===id);if(ix>=0)rec.status=DB.lessons[ix].status,rec.note=DB.lessons[ix].note,DB.lessons[ix]=rec}else DB.lessons.push(rec)}save();view.form=null;view.editLesson=null;render()};f.querySelector('#lCancel').onclick=()=>{view.form=null;view.editLesson=null;render()};
 body.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const l=DB.lessons.find(x=>x.id===b.dataset.done);if(l){l.status='done';save();render()}});
 body.querySelectorAll('[data-st]').forEach(a=>a.onclick=e=>{e.preventDefault();view.student=a.dataset.st;render()});}
function lessonMenu(id){const l=DB.lessons.find(x=>x.id===id);if(!l)return;const s=student(l.studentId);const note=prompt(`Урок ${fmtD(l.date)} ${l.time} · ${s?.name||''}\nТема: ${l.topic||'—'}\nСтатус: ${l.status==='done'?'проведён':l.status==='cancelled'?'отменён':'запланирован'}\n\nВведите: 1 — отметить проведённым, 2 — отменить, 3 — изменить, 4 — удалить, или текст заметки «что прошли»:`,l.note||'');if(note===null)return;const v=note.trim();if(v==='1')l.status='done';else if(v==='2')l.status='cancelled';else if(v==='3'){view.editLesson=l;view.form='lesson';render();return}else if(v==='4'){DB.lessons=DB.lessons.filter(x=>x.id!==id)}else{l.note=v;if(l.status==='planned'&&l.date<=todayISO())l.status='done'}save();render()}
function renderStudents(body){
 body.innerHTML=`<div class="cab-row"><button class="cab-btn" id="sAdd">+ Ученик</button><span class="cab-muted">${DB.students.length} учеников</span></div>${view.form==='student'?studentForm():''}<div class="cab-grid">${DB.students.map(s=>{const b=balance(s.id),nl=nextLesson(s.id);return `<button class="cab-card" data-st="${s.id}"><b>${esc(s.name)}</b><small>${s.exam==='ege'?'ЕГЭ':'ОГЭ'} · ${esc((s.subjects||[]).join(', ')||'предмет не указан')}${s.grade?' · '+esc(s.grade)+' класс':''}</small><small>${nl?'Следующий урок: '+fmtD(nl.date)+' '+esc(nl.time):'Уроки не запланированы'}</small><div style="margin-top:6px"><span class="cab-pill ${b.left<0?'bad':b.left===0?'warn':''}">${b.left<0?'долг '+(-b.left)+' ур.':b.left===0?'оплата закончилась':'оплачено '+b.left+' ур.'}</span></div></button>`}).join('')||'<div class="cab-muted">Добавьте первого ученика — карточка покажет расписание, домашние задания и оплату.</div>'}</div>`;
 body.querySelector('#sAdd').onclick=()=>{view.form=view.form==='student'?null:'student';view.editStudent=null;render()};bindStudentForm(body);
 body.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>{view.student=b.dataset.st;view.form=null;render()});}
function studentForm(){const s=view.editStudent||{};const subs=V4.subjects();return `<form class="cab-form" id="sForm"><input type="hidden" name="id" value="${s.id||''}"><div><label>Имя</label><input name="name" value="${esc(s.name||'')}" required placeholder="Имя Фамилия"></div><div><label>Экзамен</label><select name="exam"><option value="oge" ${s.exam!=='ege'?'selected':''}>ОГЭ</option><option value="ege" ${s.exam==='ege'?'selected':''}>ЕГЭ</option></select></div><div><label>Класс</label><input name="grade" value="${esc(s.grade||'')}" placeholder="9"></div><div><label>Цена урока, ₽</label><input type="number" name="price" value="${s.price||''}" placeholder="1500"></div><div class="full"><label>Предметы (через запятую)</label><input name="subjects" value="${esc((s.subjects||[]).join(', '))}" placeholder="Математика, Физика"></div><div class="full"><label>Контакт родителя / заметки</label><input name="note" value="${esc(s.note||'')}" placeholder="телефон, пожелания, цель"></div><div class="full cab-row"><button class="cab-btn" type="submit">${s.id?'Сохранить':'Добавить ученика'}</button><button class="cab-btn sec" type="button" id="sCancel">Отмена</button></div></form>`}
function bindStudentForm(body){const f=body.querySelector('#sForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);const id=fd.get('id');const rec={id:id||uid(),name:String(fd.get('name')).trim(),exam:fd.get('exam'),grade:String(fd.get('grade')||'').trim(),price:Number(fd.get('price'))||0,subjects:String(fd.get('subjects')||'').split(',').map(x=>x.trim()).filter(Boolean),note:String(fd.get('note')||'').trim(),created:Date.now()};if(id){const ix=DB.students.findIndex(x=>x.id===id);if(ix>=0)DB.students[ix]={...DB.students[ix],...rec}}else DB.students.push(rec);save();view.form=null;view.editStudent=null;if(!id)view.student=rec.id;render()};f.querySelector('#sCancel').onclick=()=>{view.form=null;view.editStudent=null;render()}}
function subjectIdFor(s){const subs=V4.subjects();const want=(s.subjects||[])[0]||'';const cand=subs.filter(x=>x.exam===(s.exam||'oge'));return (cand.find(x=>x.name.toLowerCase()===want.toLowerCase())||cand.find(x=>want&&x.name.toLowerCase().startsWith(want.toLowerCase().slice(0,4)))||cand[0])?.id}
async function renderStudent(body){
 const s=student(view.student);if(!s){view.student=null;render();return}
 const b=balance(s.id),ls=lessonsOf(s.id),nl=nextLesson(s.id),ld=lastDone(s.id),hw=DB.homework.filter(h=>h.studentId===s.id).sort((a,b)=>b.created-a.created);
 const subs=V4.subjects().filter(x=>x.exam===(s.exam||'oge'));
 body.innerHTML=`<div class="cab-row"><button class="cab-btn sec sm" id="stBack">← Ученики</button><button class="cab-btn sec sm" id="stEdit">Изменить</button><button class="cab-btn danger sm" id="stDel">Удалить</button><span class="cab-muted">${s.exam==='ege'?'ЕГЭ':'ОГЭ'}${s.grade?' · '+esc(s.grade)+' класс':''} · ${esc((s.subjects||[]).join(', ')||'предмет не указан')}${s.note?' · '+esc(s.note):''}</span></div>
 ${view.form==='student'?studentForm():''}
 <div class="cab-stats"><div class="cab-stat"><b>${b.done}</b><span>уроков проведено</span></div><div class="cab-stat"><b>${b.left}</b><span>оплачено вперёд</span></div><div class="cab-stat"><b>${money(b.paidMoney)}</b><span>получено всего</span></div><div class="cab-stat"><b>${nl?fmtD(nl.date)+' '+esc(nl.time):'—'}</b><span>следующий урок</span></div></div>
 <div class="cab-sec"><h3>Что проходим сейчас</h3>${ld?`<div><b>Последний урок ${fmtD(ld.date)}:</b> ${esc(ld.topic||'тема не указана')}${ld.note?'<br><span class="cab-muted">Заметка: '+esc(ld.note)+'</span>':''}</div>`:'<div class="cab-muted">Проведённых уроков ещё нет.</div>'}${nl?`<div style="margin-top:6px"><b>Следующий:</b> ${fmtD(nl.date)} ${esc(nl.time)} · ${esc(nl.topic||'тема не задана')}</div>`:''}<div class="cab-row" style="margin-top:8px"><button class="cab-btn sm" id="stLesson">+ Урок</button><button class="cab-btn sec sm" id="stRoom">Открыть комнату занятия</button></div>${view.form==='lesson'?lessonForm(s.id):''}</div>
 <div class="cab-sec"><h3>Домашнее задание</h3><div class="cab-row"><label class="cab-muted">Предмет: <select id="hwSub">${subs.map(x=>`<option value="${x.id}" ${x.id===subjectIdFor(s)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><button class="cab-btn sm" id="hwNew">Составить и отправить</button></div><div id="hwList">${hw.length?'<table class="cab-t"><tr><th>Дата</th><th>Вариант</th><th>Результат</th><th></th></tr>'+hw.map(h=>`<tr><td>${new Date(h.created).toLocaleDateString('ru-RU')}</td><td>${esc(h.label)}</td><td id="hw-${h.id}">…</td><td><button class="cab-btn sec sm" data-hwj="${h.journalId}">Журнал</button> <button class="cab-btn sec sm" data-hwl="${h.id}">Ссылка</button></td></tr>`).join('')+'</table>':'<div class="cab-muted">Домашних заданий пока нет. Выберите предмет и нажмите «Составить и отправить»: откроется конструктор варианта, ссылка привяжется к ученику.</div>'}</div></div>
 <div class="cab-sec"><h3>Оплата</h3><div class="cab-row"><button class="cab-btn sm" id="payAdd">+ Оплата</button>${s.price?`<span class="cab-muted">цена урока ${money(s.price)}</span>`:''}</div>${view.form==='pay'?payForm(s):''}${paymentsOf(s.id).length?'<table class="cab-t"><tr><th>Дата</th><th>Сумма</th><th>Уроков</th><th>Комментарий</th><th></th></tr>'+paymentsOf(s.id).map(p=>`<tr><td>${fmtD(p.date)}</td><td>${money(p.amount)}</td><td>${p.lessons}</td><td>${esc(p.note||'')}</td><td><button class="cab-btn danger sm" data-pdel="${p.id}">×</button></td></tr>`).join('')+'</table>':'<div class="cab-muted">Платежей нет.</div>'}</div>
 <div class="cab-sec"><h3>История уроков</h3>${ls.length?'<table class="cab-t"><tr><th>Дата</th><th>Время</th><th>Тема</th><th>Статус</th><th>Заметка</th></tr>'+ls.slice().reverse().map(l=>`<tr><td>${fmtD(l.date)}</td><td>${esc(l.time)}</td><td>${esc(l.topic||'')}</td><td>${l.status==='done'?'<span class="cab-pill">проведён</span>':l.status==='cancelled'?'<span class="cab-pill bad">отменён</span>':'<span class="cab-pill warn">план</span>'} <button class="cab-btn sec sm" data-l="${l.id}">…</button></td><td>${esc(l.note||'')}</td></tr>`).join('')+'</table>':'<div class="cab-muted">Уроков нет.</div>'}</div>`;
 body.querySelector('#stBack').onclick=()=>{view.student=null;view.tab='students';render()};
 body.querySelector('#stEdit').onclick=()=>{view.editStudent=s;view.form=view.form==='student'?null:'student';render()};
 body.querySelector('#stDel').onclick=()=>{if(!confirm(`Удалить ученика ${s.name} вместе с уроками и платежами?`))return;DB.students=DB.students.filter(x=>x.id!==s.id);DB.lessons=DB.lessons.filter(x=>x.studentId!==s.id);DB.payments=DB.payments.filter(x=>x.studentId!==s.id);DB.homework=DB.homework.filter(x=>x.studentId!==s.id);save();view.student=null;render()};
 body.querySelector('#stLesson').onclick=()=>{view.editLesson=null;view.form=view.form==='lesson'?null:'lesson';render()};
 body.querySelector('#stRoom').onclick=()=>{dlg.close();d.querySelector('#roomOpen')?.click()};
 body.querySelector('#hwNew').onclick=()=>{const sub=body.querySelector('#hwSub').value;window.cabinetStudentId=s.id;dlg.close();V4.buildVariant(sub);const pk=V4.openDialog();if(!pk.open)pk.showModal();whenClosed(pk,()=>{window.cabinetStudentId=null;view.student=s.id;open()})};
 body.querySelectorAll('[data-hwj]').forEach(b=>b.onclick=()=>{const j=journals().find(x=>x.id===b.dataset.hwj)||{id:b.dataset.hwj,label:'Вариант'};dlg.close();V4.journalView(j);const pk=V4.openDialog();if(!pk.open)pk.showModal();whenClosed(pk,()=>{view.student=s.id;open()})});
 body.querySelectorAll('[data-hwl]').forEach(b=>b.onclick=async()=>{const h=DB.homework.find(x=>x.id===b.dataset.hwl);try{await navigator.clipboard.writeText(h.link);b.textContent='Скопировано'}catch{prompt('Ссылка на вариант:',h.link)}});
 body.querySelector('#payAdd').onclick=()=>{view.form=view.form==='pay'?null:'pay';render()};bindPayForm(body,s);
 body.querySelectorAll('[data-pdel]').forEach(b=>b.onclick=()=>{DB.payments=DB.payments.filter(p=>p.id!==b.dataset.pdel);save();render()});
 body.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>lessonMenu(b.dataset.l));bindLessonForm(body);bindStudentForm(body);
 // результаты домашних заданий из журнала
 for(const h of hw){const cell=body.querySelector('#hw-'+h.id);if(!cell)continue;fetch(V4.JOURNAL_API+h.journalId).then(r=>r.json()).then(j=>{const rows=(j.results||[]).filter(r=>r.name);if(!rows.length){cell.innerHTML='<span class="cab-pill warn">не открыто</span>';return}const done=rows.filter(r=>r.done).slice(-1)[0];const ok=rows.filter(r=>r.qid&&r.ok).length,all=rows.filter(r=>r.qid).length;cell.innerHTML=done?`<span class="cab-pill">${done.score}/${done.total}</span>`:`<span class="cab-pill warn">в работе ${ok}/${all}</span>`}).catch(()=>{cell.textContent='—'})}
}
function payForm(s){return `<form class="cab-form" id="pForm"><div><label>Дата</label><input type="date" name="date" value="${todayISO()}" required></div><div><label>Сумма, ₽</label><input type="number" name="amount" value="${s.price?s.price*4:''}" required></div><div><label>Оплачено уроков</label><input type="number" name="lessons" value="${s.price?4:1}" min="0" required></div><div class="full"><label>Комментарий</label><input name="note" placeholder="перевод на карту, наличные…"></div><div class="full cab-row"><button class="cab-btn" type="submit">Записать оплату</button><button class="cab-btn sec" type="button" id="pCancel">Отмена</button></div></form>`}
function bindPayForm(body,s){const f=body.querySelector('#pForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);DB.payments.push({id:uid(),studentId:s.id,date:fd.get('date'),amount:Number(fd.get('amount'))||0,lessons:Number(fd.get('lessons'))||0,note:String(fd.get('note')||'').trim()});save();view.form=null;render()};f.querySelector('#pCancel').onclick=()=>{view.form=null;render()}}
function renderPay(body){const m=todayISO().slice(0,7);const rows=DB.students.map(s=>{const b=balance(s.id);const monthDone=lessonsOf(s.id).filter(l=>l.status==='done'&&l.date.startsWith(m)).length;const monthPaid=paymentsOf(s.id).filter(p=>p.date.startsWith(m)).reduce((a,p)=>a+p.amount,0);return{s,b,monthDone,monthPaid}});const total=rows.reduce((a,r)=>a+r.monthPaid,0),debt=rows.filter(r=>r.b.left<0);
 body.innerHTML=`<div class="cab-stats"><div class="cab-stat"><b>${money(total)}</b><span>получено в этом месяце</span></div><div class="cab-stat"><b>${rows.reduce((a,r)=>a+r.monthDone,0)}</b><span>уроков проведено в месяце</span></div><div class="cab-stat"><b>${debt.length}</b><span>учеников с долгом</span></div></div><div class="cab-sec"><h3>По ученикам</h3>${rows.length?'<table class="cab-t"><tr><th>Ученик</th><th>Проведено всего</th><th>Оплачено вперёд</th><th>В этом месяце</th><th>Получено всего</th></tr>'+rows.map(r=>`<tr><td><a href="#" data-st="${r.s.id}">${esc(r.s.name)}</a></td><td>${r.b.done}</td><td><span class="cab-pill ${r.b.left<0?'bad':r.b.left===0?'warn':''}">${r.b.left}</span></td><td>${money(r.monthPaid)} · ${r.monthDone} ур.</td><td>${money(r.b.paidMoney)}</td></tr>`).join('')+'</table>':'<div class="cab-muted">Учеников нет.</div>'}</div>`;
 body.querySelectorAll('[data-st]').forEach(a=>a.onclick=e=>{e.preventDefault();view.student=a.dataset.st;render()})}
function renderCode(body){const c=code();const em=email();const step=view.loginStep||'email';
 const loginHtml=em?`<div class="cab-sec"><h3>Аккаунт</h3><p class="cab-muted">Вы вошли как <b>${esc(em)}</b>. Кабинет сохраняется на сервере и открывается на любом устройстве после входа по этой почте.</p><div class="cab-row"><button class="cab-btn sec sm" id="aPush">Сохранить на сервер сейчас</button><button class="cab-btn danger sm" id="aLogout">Выйти на этом устройстве</button></div></div>`
 :`<div class="cab-sec"><h3>Вход по почте</h3><p class="cab-muted">Введите почту — пришлём код из 6 цифр. Пароль не нужен. После входа кабинет будет доступен на любом устройстве.</p>${step==='email'?`<form class="cab-form" id="aForm"><div class="full"><label>Почта</label><input type="email" name="email" required placeholder="you@example.com" value="${esc(view.loginEmail||'')}"></div><div class="full cab-row"><button class="cab-btn" type="submit">Получить код</button><span class="cab-muted" id="aMsg"></span></div></form>`:`<form class="cab-form" id="aForm2"><div class="full"><label>Код из письма на ${esc(view.loginEmail)}</label><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required placeholder="123456" autocomplete="one-time-code"></div><div class="full cab-row"><button class="cab-btn" type="submit">Войти</button><button class="cab-btn sec" type="button" id="aBack">Другая почта</button><span class="cab-muted" id="aMsg"></span></div></form>`}</div>`;
 body.innerHTML=loginHtml+`<div class="cab-sec"><h3>${em?'Код кабинета (запасной способ)':'Синхронизация по коду (без почты)'}</h3><p class="cab-muted">Кабинет хранится в этом браузере. Чтобы открыть его на телефоне или другом компьютере, включите синхронизацию: данные будут сохраняться на сервере под кодом кабинета. Код — это ключ доступа, никому его не передавайте.</p>${c?`<div class="cab-row"><b style="font-family:ui-monospace,Menlo,monospace;font-size:18px;letter-spacing:.1em">${c}</b><button class="cab-btn sec sm" id="cCopy">Скопировать</button><button class="cab-btn sec sm" id="cPush">Сохранить на сервер сейчас</button><button class="cab-btn danger sm" id="cOff">Отключить</button></div>`:`<div class="cab-row"><button class="cab-btn" id="cNew">Включить синхронизацию</button></div>`}<div class="cab-row"><label class="cab-muted">Войти по коду с другого устройства: <input id="cIn" placeholder="16 символов" style="border:1px solid #ccd6cf;border-radius:10px;padding:8px;font-size:16px;width:220px"></label><button class="cab-btn sec sm" id="cLogin">Войти</button></div></div>
 <div class="cab-sec"><h3>Резервная копия</h3><div class="cab-row"><button class="cab-btn sec sm" id="cExport">Скачать JSON</button><label class="cab-btn sec sm" style="cursor:pointer">Загрузить JSON <input type="file" id="cImport" accept="application/json" hidden></label></div></div>`;
 body.querySelector('#cNew')?.addEventListener('click',()=>{try{localStorage.setItem(KEY_CODE,newCode())}catch{}pushRemote();render()});
 body.querySelector('#cCopy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(c)}catch{}});
 body.querySelector('#cPush')?.addEventListener('click',()=>pushRemote());
 body.querySelector('#cOff')?.addEventListener('click',()=>{if(confirm('Отключить синхронизацию? Данные останутся в этом браузере.')){try{localStorage.removeItem(KEY_CODE)}catch{}render()}});
 body.querySelector('#cLogin').onclick=async()=>{const v=body.querySelector('#cIn').value.trim().toLowerCase();if(!/^[a-z0-9]{16}$/.test(v)){alert('Код должен содержать 16 латинских букв и цифр.');return}const ok=await pullRemote(v);if(ok){try{localStorage.setItem(KEY_CODE,v)}catch{}view.tab='students';render()}else alert('Кабинет с таким кодом не найден или нет связи.')};
 const msg=t=>{const m=body.querySelector('#aMsg');if(m)m.textContent=t};
 const f1=body.querySelector('#aForm');if(f1)f1.onsubmit=async e=>{e.preventDefault();const em2=new FormData(f1).get('email').trim().toLowerCase();view.loginEmail=em2;msg('Отправляем…');const r=await authFetch('request',{email:em2});if(r.ok){view.loginStep='code';render()}else msg(r.error||'Ошибка отправки')};
 const f2=body.querySelector('#aForm2');if(f2){f2.onsubmit=async e=>{e.preventDefault();msg('Проверяем…');const r=await authFetch('verify',{email:view.loginEmail,code:new FormData(f2).get('code')});if(!r.ok){msg(r.error||'Неверный код');return}ls.set(KEY_TOK,r.token);ls.set(KEY_MAIL,r.email);const hadLocal=DB.students.length>0&&!code();ls.set(KEY_CODE,r.cabinet);view.loginStep='email';if(hadLocal){const remote=await fetch(API+r.cabinet).then(x=>x.json()).catch(()=>null);if(!remote||!Array.isArray(remote.students)||!remote.students.length){await pushRemote();view.tab='students';render();return}}await pullRemote(r.cabinet);view.tab='students';render()};body.querySelector('#aBack').onclick=()=>{view.loginStep='email';render()}}
 body.querySelector('#aPush')?.addEventListener('click',()=>pushRemote());
 body.querySelector('#aLogout')?.addEventListener('click',async()=>{if(!confirm('Выйти на этом устройстве? Данные на сервере сохранятся.'))return;await authFetch('logout',{}).catch(()=>{});ls.del(KEY_TOK);ls.del(KEY_MAIL);ls.del(KEY_CODE);render()});
 body.querySelector('#cExport').onclick=()=>{const a=d.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(DB,null,1));a.download='kabinet-repetitora.json';a.click()};
 body.querySelector('#cImport').onchange=e=>{const f=e.target.files[0];if(!f)return;f.text().then(t=>{const j=JSON.parse(t);if(j&&Array.isArray(j.students)){DB=j;save();render()}else alert('Файл не похож на резервную копию кабинета.')}).catch(()=>alert('Не удалось прочитать файл.'))};}

// кнопка в шапке
const top=d.querySelector('.topright');if(top){const b=d.createElement('button');b.className='cab-btn-top';b.id='cabinetOpen';b.textContent='Кабинет';b.onclick=open;top.insertBefore(b,top.querySelector('#roomOpen'))}
window.tutorCabinet={open,get data(){return DB}};
})();
